# Pages CMS config for https://github.com/BryanHogan/learnkorean (Astro Starlight)

# Where uploaded images/files live in your repo (and how they are referenced on the site)
media:
  input: public/images
  output: /images
  # Optionally show only image types in the picker:
  categories: [ image ]

# Content models
content:
  - name: docs
    label: Docs
    type: collection
    path: src/content/docs
    subfolders: true

    # How created files are named; {primary} = first field in `view.fields` (title here)
    filename: "{primary}.md"

    # Collection listing UI defaults in PagesCMS
    view:
      # Show a tree view using index.md as folder nodes (great for Starlight)
      layout: tree
      node:
        filename: index.md
        hideDirs: none
      # Fields to display in the table/list
      fields: [ title, draft, lastUpdated ]
      # Sort options and defaults
      sort: [ lastUpdated, title ]
      default:
        sort: lastUpdated
        order: desc

    # Schema mapping to Starlight frontmatter + the Markdown body
    format: yaml-frontmatter
    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: description
        label: Description
        type: text
        description: Short summary used for SEO and previews.

      - name: slug
        label: Custom slug
        type: string
        description: Optional. Overrides the page route if needed.

      - name: draft
        label: Draft
        type: boolean
        default: false
        description: If true, the page won’t be published.

      - name: lastUpdated
        label: Last updated
        type: date
        description: Optional. Shown in the Starlight UI if configured.

      - name: template
        label: Template
        type: select
        options:
          - label: Doc (default)
            value: doc
          - label: Splash (landing)
            value: splash
        default: doc
        description: Starlight layout for this page.

      - name: tableOfContents
        label: Table of contents
        type: object
        required: false
        description: Set to false to hide ToC, or specify heading levels.
        fields:
          - name: minHeadingLevel
            label: Min heading level
            type: number
            default: 2
          - name: maxHeadingLevel
            label: Max heading level
            type: number
            default: 4

      - name: hero
        label: Hero (Splash only)
        type: object
        required: false
        fields:
          - name: title
            label: Hero title
            type: string
          - name: tagline
            label: Tagline
            type: text
          - name: image
            label: Hero image
            type: object
            fields:
              - name: alt
                label: Alt text
                type: string
              - name: file
                label: File
                type: image
          - name: actions
            label: Actions
            type: object
            list: true
            fields:
              - name: text
                label: Button text
                type: string
              - name: link
                label: Link
                type: string
              - name: icon
                label: Icon (Starlight icon name)
                type: string
              - name: variant
                label: Variant
                type: select
                options:
                  - minimal
                  - primary
                  - secondary

      - name: banner
        label: Banner
        type: object
        required: false
        fields:
          - name: content
            label: Content
            type: text
          - name: dismissible
            label: Dismissible
            type: boolean
            default: true
          - name: variant
            label: Variant
            type: select
            options:
              - info
              - warning
              - danger
              - success

      - name: sidebar
        label: Sidebar options
        type: object
        required: false
        fields:
          - name: label
            label: Sidebar label
            type: string
            description: Override the text shown in the sidebar.
          - name: order
            label: Order
            type: number
            description: Controls ordering within a folder.

      - name: editUrl
        label: Edit URL
        type: string
        description: Override global edit link or disable with false.

      - name: pagefind
        label: Pagefind options
        type: object
        required: false
        fields:
          - name: exclude
            label: Exclude from search
            type: boolean
            default: false

      - name: body
        label: Content
        type: rich-text
        description: Markdown content of the page.

# Optional: global repo/branch settings
settings:
  content:
    # Merge updates into existing frontmatter instead of overwriting the file,
    # handy when you have custom keys not exposed in the form.
    merge: true
